require 'rubygems'
require 'bundler/setup'
require 'screenleap'
require 'vcr'
require 'webmock'
require 'webmock/rspec'

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end

# VCR configuration
#
# see https://github.com/vcr/vcr
# https://www.relishapp.com/vcr/vcr/v/2-0-0/docs/test-frameworks/usage-with-rspec-metadata
# https://www.relishapp.com/vcr/vcr/v/1-6-0/docs/cassettes/automatic-re-recording
# https://relishapp.com/vcr/vcr/v/1-10-0/docs/configuration/filter-sensitive-data
VCR.configure do |config|
  config.cassette_library_dir = 'spec/fixtures/vcr_cassettes'
  config.hook_into :webmock
  config.allow_http_connections_when_no_cassette = true
  config.configure_rspec_metadata!
  config.filter_sensitive_data('<ACCOUNTID>') { ENV['SCREENLEAP_ACCOUNTID'] }
  config.filter_sensitive_data('<AUTHTOKEN>') { ENV['SCREENLEAP_AUTHTOKEN'] }
end
